"""
Data source configuration for the commons-au pipeline.

Each source defines:
- id: unique identifier used for filenames and tracking
- name: human-readable name of the dataset
- organisation: the government agency that publishes it
- jurisdiction: state/territory or "federal"
- url: direct download URL for the CSV
- license: the license identifier
- license_url: link to the license text
- dataset_url: link to the dataset page on the portal
- field_map: mapping from source column names to our schema fields
"""

SCHEMA_FIELDS = [
    "id",
    "name",
    "description",
    "category",
    "address",
    "suburb",
    "state",
    "postcode",
    "latitude",
    "longitude",
    "phone",
    "email",
    "website",
    "hours",
    "eligibility",
    "cost",
    "source_id",
    "source_name",
    "source_organisation",
    "source_jurisdiction",
    "source_license",
    "source_url",
    "source_date",
]

CATEGORIES = {
    # Mapping from various source labels to our standard categories
    "drug and alcohol": "alcohol_drugs",
    "needle exchange": "alcohol_drugs",
    "counselling and psychiatric services": "mental_health",
    "mental health": "mental_health",
    "health services / pharmacy": "health",
    "health services": "health",
    "health": "health",
    "doctor": "health",
    "dental": "health",
    "food": "food",
    "meals": "food",
    "food relief": "food",
    "pantry/groceries": "food",
    "hot meals": "food",
    "accommodation": "housing",
    "housing": "housing",
    "emergency accommodation": "housing",
    "legal": "legal",
    "legal services": "legal",
    "material aid / financial aid": "financial",
    "financial aid": "financial",
    "financial crisis and material aid - emergency relief": "financial",
    "centrelink": "financial",
    "employment": "employment",
    "disability employment": "employment",
    "education": "education",
    "disability": "disability",
    "family services": "family",
    "domestic violence": "family",
    "recreation": "community",
    "community": "community",
    "information and referral": "information",
    "transport": "transport",
    "technology": "technology",
    "personal care": "personal_care",
    # SA Community Directory categories
    "community organisation": "community",
    "community organisations": "community",
    "community support": "community",
    "welfare": "financial",
    "welfare services": "financial",
    "churches": "community",
    "sport": "community",
    "sporting clubs": "community",
    "government": "information",
    "government services": "information",
    "support groups": "community",
    "self help": "community",
    "aged care": "health",
    "youth": "community",
    "children": "family",
    "childcare": "family",
    "women": "family",
    "multicultural": "community",
    "aboriginal": "community",
    "environment": "community",
    "arts": "community",
    "volunteer": "community",
    # QLD categories
    "crisis support": "financial",
    "victim support": "legal",
    "dispute resolution": "legal",
    "screening": "health",
    "breast screening": "health",
    "housing service": "housing",
    "government service": "information",
}

SOURCES = [
    {
        "id": "vic_melbourne_helping_out",
        "name": "Free and Cheap Support Services (Helping Out)",
        "organisation": "City of Melbourne",
        "jurisdiction": "VIC",
        "url": "https://data.melbourne.vic.gov.au/api/v2/catalog/datasets/free-and-cheap-support-services-with-opening-hours-public-transport-and-parking-/exports/csv?delimiter=%2C",
        "license": "CC-BY-4.0",
        "license_url": "https://creativecommons.org/licenses/by/4.0/",
        "dataset_url": "https://discover.data.vic.gov.au/dataset/free-and-cheap-support-services-with-opening-hours-public-transport-and-parking-options-helping",
        "field_map": {
            "name": "name",
            "description": "what",
            "address": "address_1",
            "suburb": "suburb",
            "phone": "phone",
            "email": "email",
            "website": "website",
            "latitude": "latitude",
            "longitude": "longitude",
            "cost": "cost",
            # Hours are in separate day columns — handled in transform
            "hours_monday": "monday",
            "hours_tuesday": "tuesday",
            "hours_wednesday": "wednesday",
            "hours_thursday": "thursday",
            "hours_friday": "friday",
            "hours_saturday": "saturday",
            "hours_sunday": "sunday",
            # Categories are in separate columns — handled in transform
            "category_1": "category_1",
            "category_2": "category_2",
            "category_3": "category_3",
            "category_4": "category_4",
            "category_5": "category_5",
            "category_6": "category_6",
        },
    },
    {
        "id": "vic_casey_food_relief",
        "name": "Emergency Food Relief Groups",
        "organisation": "City of Casey",
        "jurisdiction": "VIC",
        "url": "https://data.casey.vic.gov.au/api/v2/catalog/datasets/emergency-food-relief-groups/exports/csv?delimiter=%2C",
        "license": "Other (Open)",
        "license_url": "",
        "dataset_url": "https://discover.data.vic.gov.au/dataset/emergency-food-relief-groups",
        "field_map": {
            "name": "provider",
            "description": "service_description",
            "address": "address",
            "suburb": "suburb",
            "postcode": "postcode",
            "phone": "public_telephone_no",
            "email": "email_adress",
            "website": "website",
            "latitude": "latitude",
            "longitude": "longitude",
            "hours_1": "service_hours1",
            "hours_2": "service_hours2",
        },
    },
    {
        "id": "fed_emergency_relief",
        "name": "Emergency Relief Provider Outlets",
        "organisation": "Department of Social Services",
        "jurisdiction": "federal",
        "url": "https://data.gov.au/data/dataset/d667403f-2016-463f-bb0a-3087ae67c57f/resource/0e32d958-3796-4dca-8312-489ef7a610f6/download/emergency-relief-provider-outlets-october-2016.csv",
        "license": "CC-BY-3.0-AU",
        "license_url": "https://creativecommons.org/licenses/by/3.0/au/",
        "dataset_url": "https://data.gov.au/data/dataset/d667403f-2016-463f-bb0a-3087ae67c57f",
        "field_map": {
            "name": "Outlet Name",
            "organisation_name": "Organisation Legal Name",
            "website": "Organistaion Website",
            "address": "Outlet Address",
            "suburb": "Town or Suburb",
            "postcode": "Postcode",
            "category_raw": "Activity External Name",
            "latitude": "Latitude",
            "longitude": "Longitude",
        },
    },
    {
        "id": "fed_employment_services",
        "name": "Employment Services Provider Locations and Contacts",
        "organisation": "Department of Employment and Workplace Relations",
        "jurisdiction": "federal",
        "url": "https://data.gov.au/data/dataset/638f89d7-1c12-4db9-8342-abfcd7b49e95/resource/d9c69f98-f0af-4db8-b598-513e1da748ce/download/providerdetailsmay2016.csv",
        "license": "CC-BY-3.0-AU",
        "license_url": "https://creativecommons.org/licenses/by/3.0/au/",
        "dataset_url": "https://data.gov.au/data/dataset/638f89d7-1c12-4db9-8342-abfcd7b49e95",
        "field_map": {
            "name": "SITE_NAME",
            "location_name": "LOCATION_NAME",
            "phone": "PHONE_NUMBER",
            "freecall": "AGENT_FREECALL_NUM",
            "address": "SITE_ADDRESS_LN",
            "suburb": "SITE_LOCALITY_NAME",
            "state": "SITE_STATE_CD",
            "postcode": "SITE_POSTCODE",
            "website": "SITE_URL",
            "email": "SITE_EMAIL_ADDRESS",
            "latitude": "LATITUDE",
            "longitude": "LONGITUDE",
        },
    },
    {
        "id": "sa_community_directory",
        "name": "SA Community Directory 2021",
        "organisation": "SA Community (Connecting Up Inc)",
        "jurisdiction": "SA",
        "url": "https://data.sa.gov.au/data/dataset/395caf56-f28b-4c47-aac0-4ce07a1eefc4/resource/9f28e1c2-3905-4a58-8ab0-dc07e9363840/download/sa-community-directory-2021.csv",
        "license": "CC-BY-3.0-AU",
        "license_url": "https://creativecommons.org/licenses/by/3.0/au/",
        "dataset_url": "https://data.gov.au/data/dataset/sa-community-directory",
        "field_map": {
            "name": "Org_name",
            "address": "Street_Address_Line_1",
            "address_2": "Street_Address_Line_2",
            "suburb": "Suburb",
            "state": "State",
            "postcode": "Postal_Code",
            "latitude": "Geo_Code_1_StreetAddress_",
            "longitude": "Geo_Code_2_StreetAddress_",
            "website": "Website_1",
            "phone": "Phone_1",
            "email": "Email_StreetAddress_1",
            "hours": "Organisati_Hours",
            "category_raw": "Primary_Category",
            "eligibility": "Organisati_Eligibility",
            "services": "Organisati_Services",
            "tag_line": "Organisati_Tag_Line",
            "accessibility": "Organisati_Access",
            "fees": "Organisati_Fees",
        },
    },
    {
        "id": "qld_gov_service_counters",
        "name": "Government Service Counter Locations",
        "organisation": "QLD Customer Services",
        "jurisdiction": "QLD",
        "fetch_method": "ckan_datastore",
        "ckan_api_base": "https://www.data.qld.gov.au/api/3/action/",
        "ckan_resource_id": "919a8e0f-f538-44df-bb3f-a6cccba0381f",
        "url": "https://www.data.qld.gov.au/dataset/da8ca6cd-8dca-4892-abbf-ed29b9cf7f95/resource/919a8e0f-f538-44df-bb3f-a6cccba0381f/download/website-update.csv",
        "license": "CC-BY-4.0",
        "license_url": "https://creativecommons.org/licenses/by/4.0/",
        "dataset_url": "https://www.data.qld.gov.au/dataset/government-service-counter-locations",
        "field_map": {
            "name": "Title",
            "description": "Description",
            "address": "Address 1",
            "address_2": "Address 2",
            "suburb": "Suburb",
            "state": "State",
            "postcode": "Postcode",
            "latitude": "Latitude",
            "longitude": "Longitude",
            "phone": "Phone",
            "email": "Email",
            "hours": "Operating hours",
            "wheelchair": "Wheelchair access",
            "services": "Services",
        },
    },
    {
        "id": "qld_housing_centres",
        "name": "Contact a Housing Service Centre",
        "organisation": "QLD Housing and Public Works",
        "jurisdiction": "QLD",
        "fetch_method": "ckan_datastore",
        "ckan_api_base": "https://www.data.qld.gov.au/api/3/action/",
        "ckan_resource_id": "e29680e4-a5a1-4cdf-b24d-30b4f4dff307",
        "url": "https://www.data.qld.gov.au/dataset/348d87d7-2c21-4652-8552-d1ba7f4414c5/resource/e29680e4-a5a1-4cdf-b24d-30b4f4dff307/download/housing-service-centre-contact.csv",
        "license": "CC-BY-4.0",
        "license_url": "https://creativecommons.org/licenses/by/4.0/",
        "dataset_url": "https://www.data.qld.gov.au/dataset/contact-a-housing-service-centre",
        "field_map": {
            "name": "Title",
            "address": "Address 1",
            "address_2": "Address 2",
            "suburb": "Suburb",
            "postcode": "Postcode",
            "latitude": "Latitude",
            "longitude": "Longitude",
            "phone": "Phone",
            "email": "Email",
            "hours": "Opening hours",
            "services": "Services",
        },
    },
    {
        "id": "qld_breastscreen",
        "name": "BreastScreen Queensland - Service Locations",
        "organisation": "Queensland Health",
        "jurisdiction": "QLD",
        "fetch_method": "ckan_datastore",
        "ckan_api_base": "https://www.data.qld.gov.au/api/3/action/",
        "ckan_resource_id": "76817a1a-4ffb-4235-92be-682cdd92ee17",
        "url": "https://www.data.qld.gov.au/dataset/787fcdfc-3ad3-4cb5-a3b7-4c98931a9c2e/resource/76817a1a-4ffb-4235-92be-682cdd92ee17/download/breastscreen-qld-locations-july-2023.csv",
        "license": "CC-BY-4.0",
        "license_url": "https://creativecommons.org/licenses/by/4.0/",
        "dataset_url": "https://www.data.qld.gov.au/dataset/breastscreen-queensland-service-locations",
        "field_map": {
            "name": "Title",
            "description": "Description",
            "address": "Address 1",
            "address_2": "Address 2",
            "suburb": "Suburb",
            "postcode": "Postcode",
            "latitude": "Latitude",
            "longitude": "Longitude",
            "phone": "Phone",
            "phone_2": "Phone 2",
            "email": "Email",
            "website": "Website",
        },
    },
    {
        "id": "tas_service_shops",
        "name": "Service Tasmania Shop Locations",
        "organisation": "Department of Premier and Cabinet (Tasmania)",
        "jurisdiction": "TAS",
        "url": "https://data.gov.au/data/dataset/648d7a00-96bb-40b5-ad8e-5ca51f90f441/resource/b8e618b5-2ec4-46b7-a1ce-e1fafedce05f/download/stoshops.csv",
        "license": "CC-BY-4.0",
        "license_url": "https://creativecommons.org/licenses/by/4.0/",
        "dataset_url": "https://data.gov.au/data/dataset/service-tasmania-shop-locations",
        "field_map": {
            "name": "Title",
            "address": "Address",
            "hours": "Hours",
            "latitude": "Latitude",
            "longitude": "Longitude",
        },
    },
    {
        "id": "qld_victim_support",
        "name": "List of Victim Support Services",
        "organisation": "QLD Justice",
        "jurisdiction": "QLD",
        "fetch_method": "ckan_datastore",
        "ckan_api_base": "https://www.data.qld.gov.au/api/3/action/",
        "ckan_resource_id": "e4b30413-1b44-4010-b449-c9aab4efa121",
        "url": "https://www.data.qld.gov.au/dataset/7ea8cfaf-2842-4ee0-a2db-0c260da1d08e/resource/e4b30413-1b44-4010-b449-c9aab4efa121/download/victim-support-services.csv",
        "license": "CC-BY-3.0",
        "license_url": "https://creativecommons.org/licenses/by/3.0/",
        "dataset_url": "https://www.data.qld.gov.au/dataset/list-of-victim-support-services",
        "field_map": {
            "name": "Name",
            "description": "Description",
            "phone": "Phone",
            "website": "Website",
            "category_raw": "Category",
            "audience": "Audience",
            "services": "Support services",
            "region": "Service region",
        },
    },
    {
        "id": "qld_dispute_resolution",
        "name": "Dispute Resolution Centres",
        "organisation": "QLD Justice",
        "jurisdiction": "QLD",
        "fetch_method": "ckan_datastore",
        "ckan_api_base": "https://www.data.qld.gov.au/api/3/action/",
        "ckan_resource_id": "94fa3715-1a91-43f5-909b-c6a2502e5ffb",
        "url": "https://www.data.qld.gov.au/dataset/8c00edfb-0b8d-4328-911a-57146d22194b/resource/94fa3715-1a91-43f5-909b-c6a2502e5ffb/download/dispute-resolution-centres.csv",
        "license": "CC-BY-3.0",
        "license_url": "https://creativecommons.org/licenses/by/3.0/",
        "dataset_url": "https://www.data.qld.gov.au/dataset/dispute-resolution-centres",
        "field_map": {
            "name": "Title",
            "address": "Address 1",
            "address_2": "Address 2",
            "suburb": "Suburb",
            "postcode": "Postcode",
            "latitude": "Latitude",
            "longitude": "Longitude",
            "phone": "Phone",
            "email": "Email",
            "hours": "Operating hours",
            "services": "Services",
        },
    },
    {
        "id": "qld_contacts_dccsds",
        "name": "Contacts List (DCCSDS)",
        "organisation": "QLD Families, Seniors, Disability Services and Child Safety",
        "jurisdiction": "QLD",
        "fetch_method": "ckan_datastore",
        "ckan_api_base": "https://www.data.qld.gov.au/api/3/action/",
        "ckan_resource_id": "c7ae2fe9-7c3b-4e28-abee-b917e1d810da",
        "url": "",
        "license": "CC-BY-4.0",
        "license_url": "https://creativecommons.org/licenses/by/4.0/",
        "dataset_url": "https://www.data.qld.gov.au/dataset/contacts-list-department-of-communities-child-safety-and-disability-services",
        "field_map": {
            "name": "Office",
            "description": "Service_Type",
            "address": "Address_StreetNumber_StreetName",
            "suburb": "Address_Suburb",
            "postcode": "Address_Postcode",
            "state": "Address_State",
            "phone": "Phone",
            "email": "Email",
        },
    },
    {
        "id": "qld_youth_justice_centres",
        "name": "Youth Justice Centre Locations",
        "organisation": "QLD Youth Justice",
        "jurisdiction": "QLD",
        "fetch_method": "ckan_datastore",
        "ckan_api_base": "https://www.data.qld.gov.au/api/3/action/",
        "ckan_resource_id": "dc155c0e-4a16-4a39-9bca-68cb00023c29",
        "url": "",
        "license": "CC-BY-4.0",
        "license_url": "https://creativecommons.org/licenses/by/4.0/",
        "dataset_url": "https://www.data.qld.gov.au/dataset/youth-justice-centre-locations",
        "field_map": {
            "name": "Title",
            "address": "Address 1",
            "address_2": "Address 2",
            "suburb": "Suburb",
            "postcode": "Postcode",
            "latitude": "Latitude",
            "longitude": "Longitude",
            "phone": "Phone",
            "email": "Email",
        },
    },
    {
        "id": "qld_housing_finder",
        "name": "Housing Service Finder",
        "organisation": "QLD Housing",
        "jurisdiction": "QLD",
        "fetch_method": "ckan_datastore",
        "ckan_api_base": "https://www.data.qld.gov.au/api/3/action/",
        "ckan_resource_id": "1f4c975b-f98c-4290-a662-c76c43dffbf3",
        "url": "",
        "license": "CC-BY-4.0",
        "license_url": "https://creativecommons.org/licenses/by/4.0/",
        "dataset_url": "https://www.data.qld.gov.au/dataset/housing-service-finder",
        "field_map": {
            "name": "Program title",
            "description": "Purpose",
            "services": "What's available?",
            "website": "Website",
            "eligibility": "Eligibility",
        },
    },
    {
        "id": "qld_hep_c_centres",
        "name": "Hepatitis C Testing and Treatment Centres",
        "organisation": "Queensland Health",
        "jurisdiction": "QLD",
        "fetch_method": "ckan_datastore",
        "ckan_api_base": "https://www.data.qld.gov.au/api/3/action/",
        "ckan_resource_id": "49ff30f4-182b-4ced-abe6-21438afad172",
        "url": "",
        "license": "CC-BY-4.0",
        "license_url": "https://creativecommons.org/licenses/by/4.0/",
        "dataset_url": "https://www.data.qld.gov.au/dataset/hepatitis-c-testing-and-treatment-centres",
        "field_map": {
            "name": "Facility",
            "address": "Street Address",
            "postcode": "Postcode",
            "latitude": "Latitude",
            "longitude": "Longitude",
            "phone": "Phone",
            "category_raw": "Category",
        },
    },
    {
        "id": "vic_ballarat_food",
        "name": "Ballarat Community Food Activities",
        "organisation": "City of Ballarat",
        "jurisdiction": "VIC",
        "url": "https://data.gov.au/data/dataset/70374622-81eb-4e84-ac43-587e4a4b8121/resource/7643818a-35f5-4560-b795-e4cc48aa656c/download/ballaratcommunityfoodactivities.csv",
        "license": "CC-BY-3.0-AU",
        "license_url": "https://creativecommons.org/licenses/by/3.0/au/",
        "dataset_url": "https://data.gov.au/data/dataset/ballarat-community-food-activities",
        "field_map": {
            "name": "Name",
            "address": "Address",
            "category_raw": "Type",
            "latitude": "lat",
            "longitude": "long",
        },
    },
    {
        "id": "vic_ballarat_community_centres",
        "name": "Ballarat Community Centres and Halls",
        "organisation": "City of Ballarat",
        "jurisdiction": "VIC",
        "url": "https://data.gov.au/data/dataset/6fcc02e3-86dc-4c82-8f7c-be0f76729b10/resource/3dd25411-da4d-493b-bf20-b9dda6002d32/download/ballarathallscommunitycentres.csv",
        "license": "CC-BY-3.0-AU",
        "license_url": "https://creativecommons.org/licenses/by/3.0/au/",
        "dataset_url": "https://data.gov.au/data/dataset/ballarat-community-centres-and-halls",
        "field_map": {
            "name": "Facility",
            "address": "Address",
            "latitude": "Lat",
            "longitude": "Long",
        },
    },
    {
        "id": "vic_neighbourhood_houses",
        "name": "Neighbourhood Houses (GFYL)",
        "organisation": "VIC Planning and Community Development",
        "jurisdiction": "VIC",
        "url": "http://data.gov.au/storage/f/2013-05-12T195634/tmpNZPwo1neighbourhood-house.csv",
        "license": "CC-BY-3.0-AU",
        "license_url": "https://creativecommons.org/licenses/by/3.0/au/",
        "dataset_url": "https://data.gov.au/data/dataset/neighbourhood-houses-gfyl",
        "field_map": {
            "name": "Name",
            "address": "Address",
            "suburb": "Suburb",
            "postcode": "Postcode",
            "state": "State",
        },
    },
    {
        "id": "vic_casey_libraries",
        "name": "Libraries Locations",
        "organisation": "City of Casey",
        "jurisdiction": "VIC",
        "url": "https://data.casey.vic.gov.au/api/v2/catalog/datasets/libraries-copy/exports/csv?delimiter=%2C",
        "license": "Other (Open)",
        "license_url": "",
        "dataset_url": "https://discover.data.vic.gov.au/dataset/libraries-locations",
        "field_map": {
            "name": "name",
            "address": "streetno",
            "suburb": "suburb",
            "postcode": "postcode",
            "latitude": "latitude",
            "longitude": "longitude",
        },
    },
    {
        "id": "vic_casey_maternal_health",
        "name": "Family Maternal Child Health Centre Locations",
        "organisation": "City of Casey",
        "jurisdiction": "VIC",
        "url": "https://data.casey.vic.gov.au/api/v2/catalog/datasets/family-maternal-child-health-centres/exports/csv?delimiter=%2C",
        "license": "Other (Open)",
        "license_url": "",
        "dataset_url": "https://discover.data.vic.gov.au/dataset/family-maternal-child-health-centre-locations",
        "field_map": {
            "name": "name",
            "description": "descript",
            "address": "streetno",
            "suburb": "suburb",
            "postcode": "postcode",
            "latitude": "latitude",
            "longitude": "longitude",
        },
    },
    {
        "id": "sa_child_family_health",
        "name": "Child and Family Health Service Centre Locations",
        "organisation": "SA Health",
        "jurisdiction": "SA",
        "url": "https://data.sa.gov.au/data/dataset/b1b64b79-e634-4c79-a52f-1680b3ef5c9c/resource/123e6bc2-6819-43ca-bae6-5daa2b23e21a/download/dprojects2015unleashed2015cafhsfilecafhscentres.csv",
        "license": "CC-BY-3.0-AU",
        "license_url": "https://creativecommons.org/licenses/by/3.0/au/",
        "dataset_url": "https://data.gov.au/data/dataset/list-of-child-and-family-health-service-centre-locations",
        "field_map": {
            "name": "Centre",
            "address": "Road/Location",
            "suburb": "Suburb",
            "postcode": "Postcode",
        },
    },
    {
        "id": "fed_judicial_courts",
        "name": "Judicial Courts",
        "organisation": "Geoscience Australia",
        "jurisdiction": "federal",
        "url": "https://d28rz98at9flks.cloudfront.net/74767/JudicialCourts_v1.csv",
        "license": "CC-BY-3.0-AU",
        "license_url": "https://creativecommons.org/licenses/by/3.0/au/",
        "dataset_url": "https://data.gov.au/data/dataset/judicial-courts",
        "field_map": {
            "name": "NAME",
            "description": "FEATURETYPE",
            "latitude": "LATITUDE",
            "longitude": "LONGITUDE",
            "state": "STATE",
        },
    },
]
