"""
Data source configuration for the commons-au pipeline.

Each source defines:
- id: unique identifier used for filenames and tracking
- name: human-readable name of the dataset
- organisation: the government agency that publishes it
- jurisdiction: state/territory or "federal"
- url: direct download URL for the CSV
- license: the license identifier
- license_url: link to the license text
- dataset_url: link to the dataset page on the portal
- field_map: mapping from source column names to our schema fields
"""

SCHEMA_FIELDS = [
    "id",
    "name",
    "description",
    "category",
    "address",
    "suburb",
    "state",
    "postcode",
    "latitude",
    "longitude",
    "phone",
    "email",
    "website",
    "hours",
    "eligibility",
    "cost",
    "source_id",
    "source_name",
    "source_organisation",
    "source_jurisdiction",
    "source_license",
    "source_url",
    "source_date",
]

CATEGORIES = {
    # Mapping from various source labels to our standard categories
    "drug and alcohol": "alcohol_drugs",
    "needle exchange": "alcohol_drugs",
    "counselling and psychiatric services": "mental_health",
    "mental health": "mental_health",
    "health services / pharmacy": "health",
    "health services": "health",
    "health": "health",
    "doctor": "health",
    "dental": "health",
    "food": "food",
    "meals": "food",
    "food relief": "food",
    "pantry/groceries": "food",
    "hot meals": "food",
    "accommodation": "housing",
    "housing": "housing",
    "emergency accommodation": "housing",
    "legal": "legal",
    "legal services": "legal",
    "material aid / financial aid": "financial",
    "financial aid": "financial",
    "financial crisis and material aid - emergency relief": "financial",
    "centrelink": "financial",
    "employment": "employment",
    "disability employment": "employment",
    "education": "education",
    "disability": "disability",
    "family services": "family",
    "domestic violence": "family",
    "recreation": "community",
    "community": "community",
    "information and referral": "information",
    "transport": "transport",
    "technology": "technology",
    "personal care": "personal_care",
}

SOURCES = [
    {
        "id": "vic_melbourne_helping_out",
        "name": "Free and Cheap Support Services (Helping Out)",
        "organisation": "City of Melbourne",
        "jurisdiction": "VIC",
        "url": "https://data.melbourne.vic.gov.au/api/v2/catalog/datasets/free-and-cheap-support-services-with-opening-hours-public-transport-and-parking-/exports/csv?delimiter=%2C",
        "license": "CC-BY-4.0",
        "license_url": "https://creativecommons.org/licenses/by/4.0/",
        "dataset_url": "https://discover.data.vic.gov.au/dataset/free-and-cheap-support-services-with-opening-hours-public-transport-and-parking-options-helping",
        "field_map": {
            "name": "name",
            "description": "what",
            "address": "address_1",
            "suburb": "suburb",
            "phone": "phone",
            "email": "email",
            "website": "website",
            "latitude": "latitude",
            "longitude": "longitude",
            "cost": "cost",
            # Hours are in separate day columns — handled in transform
            "hours_monday": "monday",
            "hours_tuesday": "tuesday",
            "hours_wednesday": "wednesday",
            "hours_thursday": "thursday",
            "hours_friday": "friday",
            "hours_saturday": "saturday",
            "hours_sunday": "sunday",
            # Categories are in separate columns — handled in transform
            "category_1": "category_1",
            "category_2": "category_2",
            "category_3": "category_3",
            "category_4": "category_4",
            "category_5": "category_5",
            "category_6": "category_6",
        },
    },
    {
        "id": "vic_casey_food_relief",
        "name": "Emergency Food Relief Groups",
        "organisation": "City of Casey",
        "jurisdiction": "VIC",
        "url": "https://data.casey.vic.gov.au/api/v2/catalog/datasets/emergency-food-relief-groups/exports/csv?delimiter=%2C",
        "license": "Other (Open)",
        "license_url": "",
        "dataset_url": "https://discover.data.vic.gov.au/dataset/emergency-food-relief-groups",
        "field_map": {
            "name": "provider",
            "description": "service_description",
            "address": "address",
            "suburb": "suburb",
            "postcode": "postcode",
            "phone": "public_telephone_no",
            "email": "email_adress",
            "website": "website",
            "latitude": "latitude",
            "longitude": "longitude",
            "hours_1": "service_hours1",
            "hours_2": "service_hours2",
        },
    },
    {
        "id": "fed_emergency_relief",
        "name": "Emergency Relief Provider Outlets",
        "organisation": "Department of Social Services",
        "jurisdiction": "federal",
        "url": "https://data.gov.au/data/dataset/d667403f-2016-463f-bb0a-3087ae67c57f/resource/0e32d958-3796-4dca-8312-489ef7a610f6/download/emergency-relief-provider-outlets-october-2016.csv",
        "license": "CC-BY-3.0-AU",
        "license_url": "https://creativecommons.org/licenses/by/3.0/au/",
        "dataset_url": "https://data.gov.au/data/dataset/d667403f-2016-463f-bb0a-3087ae67c57f",
        "field_map": {
            "name": "Outlet Name",
            "organisation_name": "Organisation Legal Name",
            "website": "Organistaion Website",
            "address": "Outlet Address",
            "suburb": "Town or Suburb",
            "postcode": "Postcode",
            "category_raw": "Activity External Name",
            "latitude": "Latitude",
            "longitude": "Longitude",
        },
    },
    {
        "id": "fed_employment_services",
        "name": "Employment Services Provider Locations and Contacts",
        "organisation": "Department of Employment and Workplace Relations",
        "jurisdiction": "federal",
        "url": "https://data.gov.au/data/dataset/638f89d7-1c12-4db9-8342-abfcd7b49e95/resource/d9c69f98-f0af-4db8-b598-513e1da748ce/download/providerdetailsmay2016.csv",
        "license": "CC-BY-3.0-AU",
        "license_url": "https://creativecommons.org/licenses/by/3.0/au/",
        "dataset_url": "https://data.gov.au/data/dataset/638f89d7-1c12-4db9-8342-abfcd7b49e95",
        "field_map": {
            "name": "SITE_NAME",
            "location_name": "LOCATION_NAME",
            "phone": "PHONE_NUMBER",
            "freecall": "AGENT_FREECALL_NUM",
            "address": "SITE_ADDRESS_LN",
            "suburb": "SITE_LOCALITY_NAME",
            "state": "SITE_STATE_CD",
            "postcode": "SITE_POSTCODE",
            "website": "SITE_URL",
            "email": "SITE_EMAIL_ADDRESS",
            "latitude": "LATITUDE",
            "longitude": "LONGITUDE",
        },
    },
]
